- JOB: intercept -g /dev/input/by-path/platform-i8042-serio-0-event-kbd | caps2esc -t 400 | space2meta | uinput -d /dev/input/by-path/platform-i8042-serio-0-event-kbd
  DEVICE:
    LINK: /dev/input/by-path/platform-i8042-serio-0-event-kbd
