- JOB: intercept -g /dev/input/by-id/usb-SINO_WEALTH_Gaming_KB-event-kbd | caps2esc -m 2 | space2meta | uinput -d /dev/input/by-id/usb-SINO_WEALTH_Gaming_KB-event-kbd
  DEVICE:
    LINK: /dev/input/by-id/usb-SINO_WEALTH_Gaming_KB-event-kbd
