#! /bin/bash

SCREENSHOT_DIR="$(xdg-user-dir PICTURES)/screenshots/"
FILE_NAME=$(date +"screenshot-%Y-%m-%d-%H-%M-%S.png")
VIEWER="feh"

notify-hypr(){
    filepath="${SCREENSHOT_DIR}/$1"
    file="$1"
    message="$2"
    wl-copy < "$file"
    action=$(notify-send "Screenshot captured" "$message" -a "Grim" -A "view=View" -i "$filepath")
    if [ -n "$action" ]; then
        if [ "$action" == "view" ]; then
            $VIEWER "$file"
        fi
    fi
}

capture_screen(){
    cd "$SCREENSHOT_DIR"
    if [ -z "$HYPRLAND_INSTANCE_SIGNATURE" ]; then
        scrot "$FILE_NAME"
        xclip -selection clipboard -t image/png -i $SCREENSHOT_DIR/`ls -1 -t $SCREENSHOT_DIR | head -1`
        notify-send "Screen captured" -a "Scrot"
    else
        grim "$FILE_NAME"
        notify-hypr "$FILE_NAME" "Screen captured $FILE_NAME and copied to clipboard"
    fi
}

capture_window(){
    cd $SCREENSHOT_DIR
    if [ -z "$HYPRLAND_INSTANCE_SIGNATURE" ]; then
        scrot -w $(xdotool getactivewindow) $FILE_NAME
        xclip -selection clipboard -t image/png -i $SCREENSHOT_DIR/`ls -1 -t $SCREENSHOT_DIR | head -1`
        notify-send "Window captured" -a "Scrot"
    else
        geometry=$(hyprctl -j -r activewindow | jq -r '"\(.at[0]),\(.at[1]) \(.size[0])x\(.size[1])"')
        grim -g "$geometry" "$FILE_NAME" || exit 1
        notify-hypr "$FILE_NAME" "Window captured ($FILE_NAME) and copied to clipboard"
    fi
}

capture_select_window(){
    cd "$SCREENSHOT_DIR"
    if [ -z "$HYPRLAND_INSTANCE_SIGNATURE" ]; then
        scrot -w $(xdotool selectwindow) "$FILE_NAME"
        xclip -selection clipboard -t image/png -i $SCREENSHOT_DIR/`ls -1 -t $SCREENSHOT_DIR | head -1`
        notify-send "Window captured" -a "Scrot"
    else
        geometry="$(hyprprop | jq -r '"\(.at[0]),\(.at[1]) \(.size[0])x\(.size[1])"')"
        grim -g "$geometry" "$FILE_NAME" || exit 1
        notify-hypr "$FILE_NAME" "Window captured ($FILE_NAME) and copied to clipboard"
    fi
}

capture_select(){
    cd "$SCREENSHOT_DIR"
    if [ -z "$HYPRLAND_INSTANCE_SIGNATURE" ]; then
        sleep 0.2 # Prevent issues on dwm
        scrot -s "$FILE_NAME"
        xclip -selection clipboard -t image/png -i $SCREENSHOT_DIR/`ls -1 -t $SCREENSHOT_DIR | head -1`
        notify-send "Selection captured" -a "Scrot"
    else
        grim -g "$(slurp)" "$FILE_NAME" || exit 1
        notify-hypr "$FILE_NAME" "Selection captured ($FILE_NAME) and copied to clipboard"
    fi
}

if ! [[ -d $SCREENSHOT_DIR/ ]]; then
    mkdir -p "$SCREENSHOT_DIR"
fi

if [[ -z $1 ]]; then
    capture_screen
elif [[ $1 == "window" ]]; then
    capture_window
elif [[ $1 == "select" ]]; then
    capture_select
elif [[ $1 == "screen" ]]; then
    capture_screen
elif [[ $1 == "select_window" ]]; then
    capture_select_window
else
    echo hi
    # echo usage
fi
