#!/usr/bin/sh

if [ "$1" = '-l' ]; then
    IMAGE_FILE="${XDG_STATE_HOME:-~/.local/state/}/lockscreen.png"
    shift
else
    IMAGE_FILE="${XDG_STATE_HOME:-~/.local/state/}/wallpaper.png"
fi

if [ -z "$1" ]
then
    feh "$IMAGE_FILE"
else
    magick "$1" -resize 1920x1080^ "${IMAGE_FILE}"
fi
