#!/usr/bin/sh

if [ -z "$1" ]
then
    feh "${XDG_STATE_HOME:-~/.local/state}/lockscreenwallpaper.png"
else
    convert "$1" -resize 1920x1080^ "${XDG_STATE_HOME:-~/.local/state}/lockscreenwallpaper.png"
fi
