#!/usr/bin/sh

setsid -f $HOME/.local/bin/startup.sh
setsid -f dwmblocks
export DESKTOP_SESSION="dwm"
while true; do
    # Log stderror to a file
    dwm 2> ${XDG_STATE_HOME:-~/.local/state}/dwm.log
    # No error logging
    # dwm >/dev/null 2>&1
    sleep 1
done
