#!/bin/sh

# Use neovim for vim if present.
[ -x "$(command -v nvim)" ] && alias vim="nvim" vimdiff="nvim -d"

# Use $XINITRC variable if file exists.
[ -f "$XINITRC" ] && alias startx="startx $XINITRC"

# Colorize commands when possible.
alias \
	ls="ls -hN --color=auto --group-directories-first" \
	grep="grep --color=auto" \
	diff="diff --color=auto" \
	ccat="highlight --out-format=ansi" \
	ip="ip -color=auto"

# These common commands are just too long! Abbreviate them.
alias \
  lsa="ls -la" \
	:e="$EDITOR" \
	v="$EDITOR" \
	p="pacman" \
	z="zathura" \
  ysy="yay -Ss " \
  yfy="yay -F " \
  cls="clear" \
  ncmpcpp="ncmpcpp -b ~/.config/ncmpcpp/bindings"

# Alternate config path to cleanup home directory
alias \
  abook="abook --datafile '${XDG_DATA_HOME}/abook/addressbook' --config '${XDG_CONFIG_HOME}/abook/abookrc'" \
	elinks="elinks --config-dir ${XDG_CONFIG_HOME}/elinks" \
	irssi="irssi --home=${XDG_DATA_HOME}/irssi"

# Prohibited commands to fix habits
# alias \
# 	rm="notify-send -a 'No Dont' 'Use trash command instead'"

# Switching prompt style, not usefull currently
# alias \
#   prompt-short="prompt_style=short" \
#   prompt-full="prompt_style=full" \
#   prompt-switch="if [[ $prompt_style == "full" ]]; then prompt-short; else prompt-full; fi"
